### ISSUE TITLE
current prices issue with resolution=5

### ISSUE THREAD

**Issue by rob0101** [amberelectric/public-api#132] opened 2023-03-06 23:34 UTC
https://api.amber.com.au/v1/sites/$API_id/prices/current?next=1&resolution=5

Reported elsewhere, but moved here for ease of tracking.

At 20 past the half hour ActualInterval gets replaced by CurrentInterval

At 25 past the half hour pricing disappears.

**Comment by jbates58** [comment] 2023-03-17 23:44
I noticed this aswell the other night. I though I was going mad. Hahaha

**Comment by madpilot** [comment] 2023-03-24 00:47
All current 5-minute intervals are now marked as `CurrentInterval` and the interval no longer disappears in the last 5-minutes of the 30-minute block.

**Closed by madpilot** 2023-03-24 00:47 UTC

**Comment by purcell-lab** [comment] 2023-03-24 07:22
Thanks @madpilot, I can confirm this has been running solid since the 10:55 interval this morning when you posted.

![image](https://user-images.githubusercontent.com/79175134/227452373-a9627f22-0643-4daa-81c7-6bdf129eb2e3.png)
